export const SELECTORS = {
    NAV_LINKS: 'a[href^="#"]',
    FORM_LOGIN: '#formLogin',
    LOGIN_USUARIO: '#usuario',
    LOGIN_SENHA: '#senha',
    LOGIN_SUBMIT: '#BotaoLogar',
    BTN_MOSTRAR_SENHA: '#mostrarSenha',
    BTN_ESQUECI_SENHA: '#esqueci',
    BTN_GOOGLE: '#google',
    FORM_CADASTRO: '#formCadastro',
    CADASTRO_NOME: '#nome',
    CADASTRO_EMAIL: '#email',
    CADASTRO_SENHA: '#senhaCadastro',
    CADASTRO_CONFIRMAR_SENHA: '#confirmarSenha',
    CADASTRO_DATA_NASCIMENTO: '#dataNascimento',
    MENSAGEM: '#mensagem',
    DASHBOARD_NOME_ALUNO: '.topo h1',
    DASHBOARD_XP_TEXTO: '.xp-topo span:last-child',
    DASHBOARD_XP_BARRA: '.barra span',
    DASHBOARD_OFENSIVA: '.sequencia h3',
    CRONOGRAMA_TABS: '.day-tab',
    CRONOGRAMA_TAB_PREFIX: '#day-tab-',
    CRONOGRAMA_BTN_ACAO: '.btn-action'
};
