export const SELECTORS = {
    NAV_LINKS: 'a[href^="#"]',
    FORM_LOGIN: '#formLogin',
    LOGIN_USUARIO: '#usuario',
    LOGIN_SENHA: '#senha',
    LOGIN_SUBMIT: '#BotaoLogar',
    BTN_MOSTRAR_SENHA: '#mostrarSenha',
    BTN_ESQUECI_SENHA: '#esqueci',
    BTN_GOOGLE: '#google',
    SECAO_LOGIN: '#secaoLogin',
    SECAO_ESQUECI: '#secaoEsqueci',
    FORM_ESQUECI: '#formEsqueci',
    RECUPERAR_EMAIL: '#recuperarEmail',
    RECUPERAR_RESPOSTA: '#recuperarResposta',
    CONTAINER_PERGUNTA_EXIBIDA: '#containerPerguntaExibida',
    TEXTO_PERGUNTA_EXIBIDA: '#textoPerguntaExibida',
    ETAPA_NOVA_SENHA: '#etapaNovaSenha',
    RECUPERAR_NOVA_SENHA: '#novaSenha',
    RECUPERAR_CONFIRMAR_SENHA: '#confirmarNovaSenha',
    BTN_MOSTRAR_NOVA_SENHA: '#mostrarNovaSenha',
    BTN_ACAO_RECUPERAR: '#btnAcaoRecuperar',
    BTN_VOLTAR_LOGIN: '#btnVoltarLogin',
    LINK_VOLTAR_LOGIN: '#linkVoltarLogin',
    BTN_GOOGLE_RECUPERAR: '#googleRecuperar',
    MENSAGEM_ESQUECI: '#mensagemEsqueci',
    FORM_CADASTRO: '#formCadastro',
    SECAO_CADASTRO: '#secaoCadastro',
    SECAO_PERGUNTA: '#secaoPergunta',
    FORM_PERGUNTA: '#formPerguntaSeguranca',
    PERGUNTA_SEGURANCA: '#perguntaSeguranca',
    PERGUNTA_CUSTOM: '#perguntaCustom',
    CAMPO_PERGUNTA_CUSTOM: '#campoPerguntaCustom',
    RESPOSTA_SEGURANCA: '#respostaSeguranca',
    BTN_VOLTAR_CADASTRO: '#btnVoltarCadastro',
    MENSAGEM_SEGURANCA: '#mensagemSeguranca',
    CADASTRO_NOME: '#nome',
    CADASTRO_EMAIL: '#email',
    CADASTRO_SENHA: '#senhaCadastro',
    CADASTRO_CONFIRMAR_SENHA: '#confirmarSenha',
    CADASTRO_DATA_NASCIMENTO: '#dataNascimento',
    MENSAGEM: '#mensagem',
    DASHBOARD_NOME_ALUNO: '.topo h1',
    DASHBOARD_XP_TEXTO: '.xp-topo span:last-child',
    DASHBOARD_XP_BARRA: '.barra span',
    DASHBOARD_OFENSIVA: '.sequencia h3',
    CRONOGRAMA_TABS: '.day-tab',
    CRONOGRAMA_TAB_PREFIX: '#day-tab-',
    CRONOGRAMA_BTN_ACAO: '.btn-action',
    DESEMPENHO_APROVEITAMENTO: '#taxaAproveitamento',
    DESEMPENHO_CIRCULO: '#circuloAproveitamento',
    DESEMPENHO_QUESTOES: '#totalQuestoes',
    DESEMPENHO_ACERTOS: '#totalAcertos',
    DESEMPENHO_ERROS: '#totalErros',
    DESEMPENHO_SIMULADOS: '#totalSimulados',
    DASHBOARD_RESUMO_QUESTOES: '#resumo-total-questoes',
    DASHBOARD_RESUMO_ACERTOS: '#resumo-total-acertos',
    DASHBOARD_RESUMO_SIMULADOS: '#resumo-total-simulados',
    DASHBOARD_RESUMO_XP: '#resumo-total-xp'
};
